version: "3.8"

services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    stop_grace_period: 30s # Allows up to 30 seconds for a graceful shutdown

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - KAFKA_TOPIC=test-topic

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER_URL=kafka:9092
      - KAFKA_TOPIC=test-topic
      - KAFKA_GROUP_ID=test-group
    stop_grace_period: 30s # Allows up to 30 seconds for a graceful shutdown

  kowl:
    image: quay.io/cloudhut/kowl:master
    depends_on:
      - kafka
    ports:
      - "8080:8080" # Kowl will be accessible on localhost:8080
    environment:
      KAFKA_BROKERS: "kafka:9092" # Connects to the Kafka broker
